#!/usr/bin/env bash
# Generate Docker Compose and SearXNG settings for multi-region VPN.
#
# Scans OPENVPN_CONFIG_DIR for subfolders containing .ovpn files.
# Each subfolder becomes a VPN+SearXNG container pair.
#
# Usage:
#   ./setup-regions.sh [config-dir]
#   Or set OPENVPN_CONFIG_DIR env var.
#
# Output:
#   docker/generated/docker-compose.regions.yml
#   docker/generated/settings-{region}.yml (one per region)
#   Prints SEARXNG_REGIONS env var to set.

set -e

CONFIG_DIR="${1:-${OPENVPN_CONFIG_DIR:?Set OPENVPN_CONFIG_DIR or pass config dir as argument}}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GEN_DIR="$SCRIPT_DIR/generated"

# Find subfolders with .ovpn files
REGIONS=()
for dir in "$CONFIG_DIR"/*/; do
  [ -d "$dir" ] || continue
  # Check if subfolder contains at least one .ovpn file
  shopt -s nullglob
  ovpn_files=("$dir"*.ovpn)
  shopt -u nullglob
  if [ ${#ovpn_files[@]} -gt 0 ]; then
    region_name="$(basename "$dir")"
    # Region names must be lowercase, digits, hyphens, underscores (used in Docker service names)
    if [[ ! "$region_name" =~ ^[a-z0-9_-]+$ ]]; then
      echo "WARNING: Skipping '$region_name' — region names must be lowercase letters, digits, hyphens, underscores" >&2
      continue
    fi
    REGIONS+=("$region_name")
  fi
done

if [ ${#REGIONS[@]} -eq 0 ]; then
  echo "No region subfolders found in $CONFIG_DIR"
  echo "To use multi-region VPN, create subfolders with .ovpn files:"
  echo "  $CONFIG_DIR/uk/  $CONFIG_DIR/jp/  $CONFIG_DIR/us/  etc."
  exit 0
fi

echo "Found ${#REGIONS[@]} region(s): ${REGIONS[*]}"

# Create output directory
mkdir -p "$GEN_DIR"

# --- Read base settings as template ---
BASE_SETTINGS="$SCRIPT_DIR/settings-vpn.yml"
if [ ! -f "$BASE_SETTINGS" ]; then
  echo "ERROR: $BASE_SETTINGS not found. Run from the docker/ directory." >&2
  exit 1
fi

# Generate a settings file by replacing the proxy section with a given proxy list
generate_settings() {
  local output_file="$1"
  local proxy_list="$2"  # newline-separated proxy entries (already indented)
  # Replace the single proxy line with the full list
  sed "/^    all:\/\/:$/,/^  [a-z]/{
    /^      - socks5:\/\//d
  }" "$BASE_SETTINGS" | sed "/^    all:\/\/:$/a\\
${proxy_list}" > "$output_file"
}

# --- Generate docker-compose.regions.yml ---
COMPOSE_FILE="$GEN_DIR/docker-compose.regions.yml"
PORT=8081
REGIONS_ENV=""

cat > "$COMPOSE_FILE" <<'HEADER'
# Auto-generated by setup-regions.sh — do not edit manually.
# Regenerate with: ./setup-regions.sh

services:
HEADER

# Check if root default.auth exists for inheritance
HAS_ROOT_AUTH=false
if [ -f "$CONFIG_DIR/default.auth" ]; then
  HAS_ROOT_AUTH=true
fi

for region in "${REGIONS[@]}"; do
  shopt -s nullglob
  ovpn_files=("$CONFIG_DIR/$region/"*.ovpn)
  shopt -u nullglob

  # Build volumes list — mount subfolder + root default.auth if it exists
  VOLUMES="      - \${OPENVPN_CONFIG_DIR}/${region}:/vpn/config:ro"
  if [ "$HAS_ROOT_AUTH" = true ] && [ ! -f "$CONFIG_DIR/$region/default.auth" ]; then
    VOLUMES="${VOLUMES}
      - \${OPENVPN_CONFIG_DIR}/default.auth:/vpn/default.auth:ro"
  fi

  vpn_index=0
  proxy_list=""
  depends_on=""

  for ovpn in "${ovpn_files[@]}"; do
    ovpn_name="$(basename "$ovpn")"

    cat >> "$COMPOSE_FILE" <<EOF
  vpn-${region}-${vpn_index}:
    build: ./vpn
    container_name: searxng-vpn-${region}-${vpn_index}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
${VOLUMES}
    environment:
      - OVPN_FILE=/vpn/config/${ovpn_name}

EOF

    # Build proxy list for settings file
    if [ -n "$proxy_list" ]; then proxy_list="${proxy_list}
"; fi
    proxy_list="${proxy_list}      - socks5://vpn-${region}-${vpn_index}:1080"

    # Build depends_on entries
    if [ -n "$depends_on" ]; then depends_on="${depends_on}
"; fi
    depends_on="${depends_on}      vpn-${region}-${vpn_index}:
        condition: service_started"

    vpn_index=$((vpn_index + 1))
  done

  # Generate SearXNG container depending on all VPN containers
  cat >> "$COMPOSE_FILE" <<EOF
  searxng-${region}:
    image: searxng/searxng:latest
    container_name: searxng-${region}
    restart: unless-stopped
    ports:
      - "${PORT}:8080"
    depends_on:
${depends_on}
    volumes:
      - ./generated/settings-${region}.yml:/etc/searxng/settings.yml:ro

EOF

  # Generate settings file with full proxy list
  generate_settings "$GEN_DIR/settings-${region}.yml" "$proxy_list"

  echo "  ${region}: ${#ovpn_files[@]} VPN container(s)"

  # Build SEARXNG_REGIONS value
  if [ -n "$REGIONS_ENV" ]; then
    REGIONS_ENV="${REGIONS_ENV},"
  fi
  REGIONS_ENV="${REGIONS_ENV}${region}=http://localhost:${PORT}"

  PORT=$((PORT + 1))
done

# --- Handle top-level .ovpn files (default instance multi-VPN) ---
shopt -s nullglob
top_level_ovpn=("$CONFIG_DIR"/*.ovpn)
shopt -u nullglob

if [ ${#top_level_ovpn[@]} -gt 1 ]; then
  echo ""
  echo "Found ${#top_level_ovpn[@]} top-level .ovpn files — generating multi-VPN for default instance"

  VPN_COMPOSE="$GEN_DIR/docker-compose.vpn-multi.yml"
  cat > "$VPN_COMPOSE" <<'HEADER'
# Auto-generated by setup-regions.sh — do not edit manually.
# Multi-VPN overlay for default SearXNG instance.

services:
HEADER

  vpn_index=0
  proxy_list=""
  depends_on=""

  for ovpn in "${top_level_ovpn[@]}"; do
    ovpn_name="$(basename "$ovpn")"

    cat >> "$VPN_COMPOSE" <<EOF
  vpn-${vpn_index}:
    build: ./vpn
    container_name: searxng-vpn-${vpn_index}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - \${OPENVPN_CONFIG_DIR}:/vpn/config:ro
    environment:
      - OVPN_FILE=/vpn/config/${ovpn_name}

EOF

    if [ -n "$proxy_list" ]; then proxy_list="${proxy_list}
"; fi
    proxy_list="${proxy_list}      - socks5://vpn-${vpn_index}:1080"

    if [ -n "$depends_on" ]; then depends_on="${depends_on}
"; fi
    depends_on="${depends_on}      vpn-${vpn_index}:
        condition: service_started"

    vpn_index=$((vpn_index + 1))
  done

  # SearXNG service override to depend on all VPN containers
  cat >> "$VPN_COMPOSE" <<EOF
  searxng:
    depends_on:
${depends_on}
    volumes:
      - ./generated/settings-vpn.yml:/etc/searxng/settings.yml:ro

EOF

  # Generate settings file with all proxies
  generate_settings "$GEN_DIR/settings-vpn.yml" "$proxy_list"

  echo "  default: ${#top_level_ovpn[@]} VPN container(s)"
  echo "  $VPN_COMPOSE"
  echo "  $GEN_DIR/settings-vpn.yml"
fi

# Write regions config — MCP server reads this automatically
REGIONS_FILE="$HOME/.mcp-searxng-regions"
echo "${REGIONS_ENV}" > "$REGIONS_FILE"
echo "SEARXNG_REGIONS=${REGIONS_ENV}" > "$GEN_DIR/.env.regions"

echo ""
echo "Generated:"
echo "  $COMPOSE_FILE"
for region in "${REGIONS[@]}"; do
  echo "  $GEN_DIR/settings-${region}.yml"
done
echo "  $REGIONS_FILE (MCP server reads this automatically)"
echo ""
echo "Start the region containers:"
echo ""
echo "  docker compose -f docker-compose.yml -f generated/docker-compose.regions.yml up -d"
echo ""
if [ ${#top_level_ovpn[@]} -gt 1 ]; then
  echo "Or with multi-VPN default instance + regions:"
  echo ""
  echo "  docker compose -f docker-compose.yml -f generated/docker-compose.vpn-multi.yml -f generated/docker-compose.regions.yml up -d"
else
  echo "Or combine with single-VPN (main instance + regions):"
  echo ""
  echo "  docker compose -f docker-compose.yml -f docker-compose.vpn.yml -f generated/docker-compose.regions.yml up -d"
fi
