#!/usr/bin/env bash
# Generate Docker Compose and SearXNG settings for multi-region VPN.
#
# Scans OPENVPN_CONFIG_DIR for subfolders containing .ovpn files.
# Each subfolder becomes a VPN+SearXNG container pair.
#
# Usage:
#   ./setup-regions.sh [config-dir]
#   Or set OPENVPN_CONFIG_DIR env var.
#
# Output:
#   docker/generated/docker-compose.regions.yml
#   docker/generated/settings-{region}.yml (one per region)
#   Prints SEARXNG_REGIONS env var to set.

set -e

CONFIG_DIR="${1:-${OPENVPN_CONFIG_DIR:?Set OPENVPN_CONFIG_DIR or pass config dir as argument}}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GEN_DIR="$SCRIPT_DIR/generated"

# Find subfolders with .ovpn files
REGIONS=()
for dir in "$CONFIG_DIR"/*/; do
  [ -d "$dir" ] || continue
  # Check if subfolder contains at least one .ovpn file
  shopt -s nullglob
  ovpn_files=("$dir"*.ovpn)
  shopt -u nullglob
  if [ ${#ovpn_files[@]} -gt 0 ]; then
    region_name="$(basename "$dir")"
    # Region names must be lowercase, digits, hyphens, underscores (used in Docker service names)
    if [[ ! "$region_name" =~ ^[a-z0-9_-]+$ ]]; then
      echo "WARNING: Skipping '$region_name' — region names must be lowercase letters, digits, hyphens, underscores" >&2
      continue
    fi
    REGIONS+=("$region_name")
  fi
done

if [ ${#REGIONS[@]} -eq 0 ]; then
  echo "No region subfolders found in $CONFIG_DIR"
  echo "To use multi-region VPN, create subfolders with .ovpn files:"
  echo "  $CONFIG_DIR/uk/  $CONFIG_DIR/jp/  $CONFIG_DIR/us/  etc."
  exit 0
fi

echo "Found ${#REGIONS[@]} region(s): ${REGIONS[*]}"

# Create output directory
mkdir -p "$GEN_DIR"

# --- Generate per-region settings files ---
# Read base settings-vpn.yml as template
BASE_SETTINGS="$SCRIPT_DIR/settings-vpn.yml"
if [ ! -f "$BASE_SETTINGS" ]; then
  echo "ERROR: $BASE_SETTINGS not found. Run from the docker/ directory." >&2
  exit 1
fi

for region in "${REGIONS[@]}"; do
  # Replace vpn:1080 with vpn-{region}:1080 in the proxy config
  sed "s|socks5://vpn:1080|socks5://vpn-${region}:1080|g" \
    "$BASE_SETTINGS" > "$GEN_DIR/settings-${region}.yml"
done

# --- Generate docker-compose.regions.yml ---
COMPOSE_FILE="$GEN_DIR/docker-compose.regions.yml"
PORT=8081
REGIONS_ENV=""

cat > "$COMPOSE_FILE" <<'HEADER'
# Auto-generated by setup-regions.sh — do not edit manually.
# Regenerate with: ./setup-regions.sh

services:
HEADER

# Check if root default.auth exists for inheritance
HAS_ROOT_AUTH=false
if [ -f "$CONFIG_DIR/default.auth" ]; then
  HAS_ROOT_AUTH=true
fi

for region in "${REGIONS[@]}"; do
  # Find first .ovpn file in the subfolder for initial connection
  shopt -s nullglob
  first_ovpn=("$CONFIG_DIR/$region/"*.ovpn)
  shopt -u nullglob
  first_ovpn_name="$(basename "${first_ovpn[0]}")"

  # Build volumes list — mount subfolder + root default.auth if it exists
  VOLUMES="      - \${OPENVPN_CONFIG_DIR}/${region}:/vpn/config:ro"
  if [ "$HAS_ROOT_AUTH" = true ] && [ ! -f "$CONFIG_DIR/$region/default.auth" ]; then
    # Mount to /vpn/default.auth — entrypoint's parent-dir fallback finds it via dirname("/vpn/config")
    VOLUMES="${VOLUMES}
      - \${OPENVPN_CONFIG_DIR}/default.auth:/vpn/default.auth:ro"
  fi

  cat >> "$COMPOSE_FILE" <<EOF
  vpn-${region}:
    build: ./vpn
    container_name: searxng-vpn-${region}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
${VOLUMES}
    environment:
      - OVPN_FILE=/vpn/config/${first_ovpn_name}
      - ROTATE_INTERVAL_MINS=\${ROTATE_INTERVAL_MINS:-30}

  searxng-${region}:
    image: searxng/searxng:latest
    container_name: searxng-${region}
    restart: unless-stopped
    ports:
      - "${PORT}:8080"
    depends_on:
      vpn-${region}:
        condition: service_started
    volumes:
      - ./generated/settings-${region}.yml:/etc/searxng/settings.yml:ro

EOF

  # Build SEARXNG_REGIONS value
  if [ -n "$REGIONS_ENV" ]; then
    REGIONS_ENV="${REGIONS_ENV},"
  fi
  REGIONS_ENV="${REGIONS_ENV}${region}=http://localhost:${PORT}"

  PORT=$((PORT + 1))
done

# Write regions config — MCP server reads this automatically
REGIONS_FILE="$HOME/.mcp-searxng-regions"
echo "${REGIONS_ENV}" > "$REGIONS_FILE"
echo "SEARXNG_REGIONS=${REGIONS_ENV}" > "$GEN_DIR/.env.regions"

echo ""
echo "Generated:"
echo "  $COMPOSE_FILE"
for region in "${REGIONS[@]}"; do
  echo "  $GEN_DIR/settings-${region}.yml"
done
echo "  $REGIONS_FILE (MCP server reads this automatically)"
echo ""
echo "Start the region containers:"
echo ""
echo "  docker compose -f docker-compose.yml -f generated/docker-compose.regions.yml up -d"
echo ""
echo "Or combine with single-VPN (main instance + regions):"
echo ""
echo "  docker compose -f docker-compose.yml -f docker-compose.vpn.yml -f generated/docker-compose.regions.yml up -d"
